name: Build Sample for Android

on: [push, pull_request]

jobs:
  apk:
    name: Apk Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          target: [Debug, Release]

    steps:
      - name: Get the Android Builder
        run: git clone https://github.com/ravbug/sdl-android-builder
      - uses: actions/checkout@v3
        with:
          submodules: true
          path: sdl-android-builder/to-build/HelloCube
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Fix CMake min required
        run: |
            cd sdl-android-builder/to-build/HelloCube/RavEngine
            sed -i -e 's/3.25/3.22/' CMakeLists.txt

      - name: Build the APK
        run: |
          cd sdl-android-builder
          ./gradlew assemble${{ matrix.target }}

      - name: Copy Assets
        run: |
            cd sdl-android-builder/app/.cxx
            assets=sdl-android-builder/app/.cxx/`find . -name "main.rvedata" -print -quit`
            cp $assets sdl-android-builder/app/src/main/assets/

      - name: Build APK with Assets
        run: |
            cd sdl-android-builder
            ./gradlew assemble${{ matrix.target }}

      - name: Upload the APK
        uses: actions/upload-artifact@v4
        with: 
          name: app-${{matrix.target}}.apk
          path: sdl-android-builder/app/build/outputs/apk/*
